### PR TITLE
Allow for text between pager buttons

### PR DESCRIPTION
**Pull request by ismyrnow**
Allows you to do the following when using the pager:

```
{{#pagination-pager pager=true ...}}
    Page x of x
{{/pagination-pager}}
```

### CODE REVIEW

**Comment by knownasilya** [comment]
So that will yield that `<li></li>` at all times, even if using it in non-block form. Make sure to wrap the yielded portion in an `{{#if hasBlock}} (http://emberjs.com/api/classes/Ember.Component.html#property_hasBlock)

**Comment by knownasilya** [comment]
I also added you as a collaborator.

**Comment by knownasilya** [comment]
Also might be a good idea to add a class to that li, so that it can be styled separately.

**Comment by ismyrnow** [comment]
Added a class of `pager-inner`.

**Comment by ismyrnow** [comment]
No longer rednering the `<li>` if the component isn't used as a block.

**Comment by knownasilya** [comment]
:+1:

**Comment by ismyrnow** [comment]
:tada:

**Comment by knownasilya** [comment]
Released as 2.2.0

**Pull request merged**
